import type { SiteSchema, SiteSection, TemplateDefinition } from "@/types/site";

const section = (id: string, type: SiteSection["type"], title: string, body: string, bg: string, fg: string, accent: string, preset: SiteSection["animation"]["preset"] = "fade-up", align: "left" | "center" = "left", items?: SiteSection["content"]["items"]): SiteSection => ({
  id, type, variant: `${type}-01`, content: { eyebrow: type === "hero" ? "Nueva colección" : undefined, title, body, cta: type === "hero" || type === "cta" ? "Descubrir más" : undefined, items }, styles: { background: bg, foreground: fg, accent, align, padding: 104 }, responsive: { hideMobile: false, mobilePadding: 48 }, animation: { preset, intensity: 55, scrub: preset === "parallax" }, locked: false,
});

const makeSite = (id: string, name: string, palette: [string, string, string], sections: SiteSection[]): SiteSchema => ({ site: { id: `demo-${id}`, name, slug: id, description: name, templateId: id, status: "draft", theme: { colors: { background: palette[0], foreground: palette[1], accent: palette[2] }, radius: 18 } }, pages: [{ id: "home", name: "Inicio", slug: "", sections }] });

export const templates: TemplateDefinition[] = [
  { id: "noir-atelier", name: "Noir Atelier", category: "Moda", description: "Editorial, silenciosa y magnética.", palette: ["#0d0b0d", "#f4eee8", "#d8b4a0"], premium: true, schema: makeSite("noir-atelier", "Noir Atelier", ["#0d0b0d", "#f4eee8", "#d8b4a0"], [section("na-1", "hero", "Vestir es construir una presencia.", "Piezas de edición limitada, trazadas entre arquitectura y movimiento.", "#0d0b0d", "#f4eee8", "#d8b4a0", "blur-reveal"), section("na-2", "gallery", "Formas que permanecen", "Una colección construida en capas, textura y pausa.", "#e8dfd6", "#181318", "#8d493a", "parallax", "center"), section("na-3", "cta", "La nueva edición ya está disponible.", "Explora el lookbook completo.", "#8d493a", "#fffaf5", "#f1c6a8", "zoom-reveal", "center")]) },
  { id: "ritual-barber", name: "Ritual 77", category: "Barbería", description: "Oscura, precisa y con carácter.", palette: ["#10100f", "#ece7da", "#c79a45"], premium: false, schema: makeSite("ritual-barber", "Ritual 77", ["#10100f", "#ece7da", "#c79a45"], [section("rb-1", "hero", "El oficio de verte impecable.", "Cortes de autor, rituales de barba y una hora que es solo tuya.", "#10100f", "#ece7da", "#c79a45", "slide-left"), section("rb-2", "services", "Rituales de la casa", "Precisión clásica con lenguaje contemporáneo.", "#1b1a17", "#ece7da", "#c79a45", "fade-up", "left", [{ title: "Corte Signature", text: "Diagnóstico, corte y styling." }, { title: "Barba Ritual", text: "Toalla caliente y perfilado." }, { title: "Reset", text: "La experiencia completa." }]), section("rb-3", "cta", "Tu silla te espera.", "Reserva en menos de un minuto.", "#c79a45", "#11100e", "#11100e", "zoom-reveal", "center")]) },
  { id: "mesa-nueve", name: "Mesa Nueve", category: "Restaurante", description: "Narrativa gastronómica editorial.", palette: ["#f0e8d8", "#251e18", "#ad3f27"], premium: false, schema: makeSite("mesa-nueve", "Mesa Nueve", ["#f0e8d8", "#251e18", "#ad3f27"], [section("mn-1", "hero", "Fuego, estación y territorio.", "Una cocina mexicana contemporánea que empieza en el mercado y termina en la memoria.", "#f0e8d8", "#251e18", "#ad3f27", "fade-up"), section("mn-2", "story", "Cada plato tiene un origen.", "Trabajamos con pequeños productores y una carta que cambia con la tierra.", "#ad3f27", "#fff7ea", "#f6c5a7", "parallax"), section("mn-3", "testimonial", "“Una cena que se siente como una conversación larga.”", "— Cuaderno Gastronómico", "#251e18", "#f0e8d8", "#ad3f27", "blur-reveal", "center")]) },
  { id: "orbital-labs", name: "Orbital Labs", category: "Agencia", description: "Tecnología con ritmo y profundidad.", palette: ["#070b16", "#eff4ff", "#6c6cff"], premium: true, schema: makeSite("orbital-labs", "Orbital Labs", ["#070b16", "#eff4ff", "#6c6cff"], [section("ol-1", "hero", "Creamos productos para la próxima órbita.", "Estrategia, diseño y tecnología para compañías que no quieren parecerse a ayer.", "#070b16", "#eff4ff", "#6c6cff", "zoom-reveal"), section("ol-2", "stats", "Impacto que se puede medir", "Sistemas digitales pensados para crecer.", "#101832", "#eff4ff", "#5de4c7", "fade-up", "left", [{ title: "43%", text: "más conversión" }, { title: "2.4×", text: "más velocidad" }, { title: "18", text: "mercados activos" }]), section("ol-3", "services", "De la señal al sistema", "Un equipo senior integrado a tu negocio.", "#eff4ff", "#0a1020", "#6c6cff", "slide-left", "left", [{ title: "Strategy", text: "Claridad antes de construir." }, { title: "Experience", text: "Interfaces con intención." }, { title: "Engineering", text: "Tecnología lista para escalar." }])]) },
  { id: "forge-athletic", name: "Forge Athletic", category: "Gimnasio", description: "Energía cinematográfica sin ruido.", palette: ["#0b0b0b", "#f2f0e9", "#ff4d27"], premium: true, schema: makeSite("forge-athletic", "Forge Athletic", ["#0b0b0b", "#f2f0e9", "#ff4d27"], [section("fa-1", "hero", "No entrenas para volver igual.", "Fuerza, movilidad y comunidad en sesiones que transforman tu ritmo.", "#0b0b0b", "#f2f0e9", "#ff4d27", "blur-reveal"), section("fa-2", "stats", "Consistencia sobre intensidad.", "Un método diseñado para durar.", "#ff4d27", "#110e0d", "#110e0d", "zoom-reveal", "left", [{ title: "45 min", text: "por sesión" }, { title: "6:1", text: "ratio de coach" }, { title: "30 días", text: "para sentir el cambio" }]), section("fa-3", "cta", "Tu primera sesión corre por nosotros.", "Ven a conocer el método Forge.", "#f2f0e9", "#101010", "#ff4d27", "slide-left", "center")]) },
  { id: "mara-visual", name: "Mara Visual", category: "Portafolio", description: "Experimental, artístico y adaptable.", palette: ["#e9ff55", "#151515", "#7559ff"], premium: false, schema: makeSite("mara-visual", "Mara Visual", ["#e9ff55", "#151515", "#7559ff"], [section("mv-1", "hero", "Imágenes para ideas que todavía no tienen nombre.", "Dirección de arte y fotografía entre Ciudad de México y cualquier parte.", "#e9ff55", "#151515", "#7559ff", "slide-left"), section("mv-2", "gallery", "Selected / 2026", "Identidades, campañas y mundos visuales.", "#7559ff", "#fff", "#e9ff55", "parallax"), section("mv-3", "contact", "Hagamos algo difícil de olvidar.", "Disponible para colaboraciones y proyectos selectos.", "#151515", "#f7f7f2", "#e9ff55", "blur-reveal", "center")]) },
];

export function cloneTemplate(templateId: string, name?: string): SiteSchema {
  const source = templates.find((item) => item.id === templateId) ?? templates[0];
  const schema = structuredClone(source.schema);
  if (name) schema.site.name = name;
  return schema;
}
