"use client";

import Link from "next/link";
import { useEffect, useRef } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { ArrowRight, Check, ChevronRight, Layers3, MousePointer2, Play, Sparkles } from "lucide-react";
import { MarketingFooter, MarketingNav } from "@/components/marketing/marketing-shell";
import { capabilityStats, plans, productFeatures, valuePillars } from "@/lib/marketing";
import { templates } from "@/lib/templates";

export function LandingPage() {
  const root = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!root.current || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;
    gsap.registerPlugin(ScrollTrigger);
    const context = gsap.context(() => {
      gsap.from("[data-hero-line]", { yPercent: 110, opacity: 0, stagger: .09, duration: 1, ease: "power4.out" });
      gsap.utils.toArray<HTMLElement>("[data-reveal]").forEach((element) => gsap.from(element, { y: 30, opacity: 0, duration: .75, ease: "power3.out", scrollTrigger: { trigger: element, start: "top 88%" } }));
    }, root);
    return () => context.revert();
  }, []);

  return <div ref={root} className="min-h-dvh overflow-hidden bg-[#08090d] text-[#f7f7f2]">
    <a href="#contenido" className="sr-only z-[100] rounded bg-white p-3 text-black focus:not-sr-only focus:fixed focus:left-3 focus:top-3">Saltar al contenido</a>
    <MarketingNav/>
    <main id="contenido">
      <section className="relative min-h-[100svh] overflow-hidden px-5 pb-16 pt-32 md:px-8 md:pt-40"><div className="pointer-events-none absolute inset-0 [background:radial-gradient(circle_at_73%_25%,rgba(139,106,255,.24),transparent_26%),radial-gradient(circle_at_20%_75%,rgba(223,255,101,.09),transparent_24%)]"/><div className="pointer-events-none absolute inset-0 opacity-[.035] [background-image:linear-gradient(white_1px,transparent_1px),linear-gradient(90deg,white_1px,transparent_1px)] [background-size:80px_80px]"/><div className="relative mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:items-end"><div><div className="inline-flex items-center gap-2 rounded-full border border-[#dfff65]/20 bg-[#dfff65]/[.06] px-3 py-2 text-xs font-medium text-[#eaff9d]"><Sparkles size={14}/>Web design de nivel global, sin una curva imposible</div><h1 className="mt-8 max-w-5xl text-[clamp(4rem,9.3vw,9.5rem)] font-semibold leading-[.8] tracking-[-.082em]"><span className="block overflow-hidden"><span data-hero-line className="block">Haz que tu</span></span><span className="block overflow-hidden"><span data-hero-line className="block text-white/35">empresa se vea</span></span><span className="block overflow-hidden"><span data-hero-line className="block bg-gradient-to-r from-[#dfff65] via-[#a7ffd4] to-[#a88aff] bg-clip-text pb-4 text-transparent">inevitable.</span></span></h1></div><div className="pb-4 lg:pb-6"><p className="max-w-xl text-lg leading-relaxed text-white/58 md:text-xl">Crea sitios multipágina con dirección visual, narrativa y movimiento de marcas globales. Vexora convierte decisiones complejas en un flujo que cualquiera puede operar.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/register" className="inline-flex min-h-13 items-center justify-center gap-3 rounded-full bg-[#dfff65] px-6 font-semibold text-[#111407] shadow-[0_16px_50px_rgba(223,255,101,.16)] transition hover:bg-white">Crear mi sitio<ArrowRight size={18}/></Link><Link href="/showcase" className="inline-flex min-h-13 items-center justify-center gap-3 rounded-full border border-white/12 bg-white/[.035] px-6 font-semibold hover:bg-white/[.08]"><Play size={17}/>Ver resultados</Link></div><p className="mt-5 text-xs text-white/35">Empieza gratis · Sin tarjeta · Edita todo cuando quieras</p></div></div><ProductStage/></div></section>

      <section className="border-y border-white/[.08] bg-[#0b0c11]"><div className="mx-auto grid max-w-[1440px] grid-cols-2 md:grid-cols-4">{capabilityStats.map(([number,label],index)=><div key={label} className={`p-6 md:p-8 ${index%2?"border-l border-white/[.07]":""} ${index>1?"border-t border-white/[.07] md:border-t-0":""} md:border-l md:first:border-l-0`}><p className="text-3xl font-semibold tracking-[-.05em] text-[#dfff65] md:text-4xl">{number}</p><p className="mt-2 max-w-[170px] text-xs leading-relaxed text-white/42">{label}</p></div>)}</div></section>

      <section className="px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1440px]"><div data-reveal className="grid gap-6 lg:grid-cols-[.7fr_1.3fr]"><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#dfff65]">La diferencia Vexora</p><h2 className="max-w-5xl text-balance text-[clamp(3rem,7vw,7rem)] font-semibold leading-[.86] tracking-[-.07em]">Resultados extraordinarios. Un proceso sorprendentemente claro.</h2></div><div className="mt-16 grid gap-4 lg:grid-cols-3">{valuePillars.map(({icon:Icon,title,text},index)=><article data-reveal key={title} className="group min-h-[340px] rounded-[2rem] border border-white/[.08] bg-white/[.025] p-7 transition duration-300 hover:border-white/20 hover:bg-white/[.045] md:p-9"><div className="flex items-start justify-between"><span className="grid size-12 place-items-center rounded-2xl border border-white/10 bg-white/[.04] text-[#dfff65]"><Icon/></span><span className="text-xs text-white/25">0{index+1}</span></div><h3 className="mt-24 text-3xl font-semibold tracking-[-.045em]">{title}</h3><p className="mt-4 max-w-sm leading-relaxed text-white/48">{text}</p></article>)}</div></div></section>

      <section className="border-y border-white/[.08] bg-[#ecebdc] px-5 py-24 text-[#10110e] md:px-8 md:py-36"><div className="mx-auto max-w-[1440px]"><div data-reveal className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#5a6330]">Multipágina desde el inicio</p><h2 className="mt-5 max-w-5xl text-[clamp(3.2rem,7vw,7rem)] font-semibold leading-[.84] tracking-[-.075em]">Tu negocio no cabe en una sola pantalla.</h2></div><p className="max-w-md text-lg leading-relaxed text-black/58">Añade páginas, duplica estructuras y publica rutas completas sin salir del editor.</p></div><div className="mt-16 grid overflow-hidden rounded-[2rem] border border-black/10 bg-[#12130f] text-white shadow-[0_35px_90px_rgba(28,30,18,.2)] lg:grid-cols-[300px_1fr]"><div className="border-b border-white/10 p-5 lg:border-b-0 lg:border-r"><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-white/35">Páginas · 4</p><div className="mt-4 space-y-2">{["Inicio","Servicios","Nosotros","Contacto"].map((page,index)=><div key={page} className={`flex min-h-12 items-center gap-3 rounded-xl px-3 text-sm ${index===0?"bg-[#dfff65] text-[#111407]":"text-white/50"}`}><Layers3 size={15}/>{page}</div>)}</div><button className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-xl border border-dashed border-white/15 text-xs text-white/55">+ Nueva página</button></div><div className="relative min-h-[430px] overflow-hidden p-5 md:p-8"><div className="absolute right-[8%] top-[4%] size-60 rounded-full bg-violet-500/25 blur-[80px]"/><div className="relative rounded-2xl border border-white/10 bg-[#090a0d] p-7 md:p-12"><p className="text-[10px] uppercase tracking-[.22em] text-[#dfff65]">Apex / Global systems</p><h3 className="mt-20 max-w-3xl text-[clamp(2.8rem,6vw,6rem)] font-semibold leading-[.86] tracking-[-.07em]">Una presencia completa. Un solo sistema.</h3><div className="mt-14 grid gap-3 sm:grid-cols-3">{["Estrategia","Experiencia","Crecimiento"].map(item=><div key={item} className="rounded-xl border border-white/10 p-4 text-xs text-white/55">{item}</div>)}</div></div></div></div></div></section>

      <section className="px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1440px]"><div data-reveal className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#dfff65]">No empiezas desde cero</p><h2 className="mt-5 max-w-4xl text-[clamp(3rem,6vw,6rem)] font-semibold leading-[.88] tracking-[-.065em]">Direcciones creativas, no plantillas genéricas.</h2></div><Link href="/templates" className="inline-flex min-h-12 items-center gap-2 self-start rounded-full border border-white/12 px-5 text-sm font-semibold hover:bg-white hover:text-black md:self-auto">Explorar las 9<ArrowRight size={16}/></Link></div><div className="mt-14 grid gap-5 md:grid-cols-3">{templates.slice(-3).map((template,index)=><Link data-reveal key={template.id} href={`/editor/demo?template=${template.id}`} className="group overflow-hidden rounded-[1.7rem] border border-white/[.09] bg-[#111218]"><div className="relative aspect-[4/5] overflow-hidden p-6" style={{background:template.palette[0],color:template.palette[1]}}><div className="absolute inset-0 opacity-70" style={{background:`radial-gradient(circle at ${72-index*18}% ${18+index*22}%,${template.palette[2]},transparent 28%)`}}/><span className="relative text-[9px] uppercase tracking-[.22em]">{template.category} · Multipágina</span><p className="relative mt-[55%] max-w-[90%] text-[clamp(2.2rem,4vw,4.2rem)] font-semibold leading-[.88] tracking-[-.065em]">{template.schema.pages[0].sections[0].content.title}</p><span className="absolute bottom-5 right-5 grid size-12 place-items-center rounded-full bg-white text-black transition group-hover:rotate-[-12deg] group-hover:scale-105"><ArrowRight/></span></div><div className="flex items-center justify-between p-5"><div><p className="font-semibold">{template.name}</p><p className="mt-1 text-xs text-white/35">3 páginas · Premium</p></div><ChevronRight className="text-white/25"/></div></Link>)}</div></div></section>

      <section className="border-y border-white/[.08] bg-[#0d0e14] px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1440px]"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#dfff65]">Todo conectado</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.055em] md:text-5xl">Menos herramientas. Más avance.</h2><p className="mt-5 max-w-md leading-relaxed text-white/48">Estructura, contenido, movimiento, responsive, medios y publicación dentro de un flujo continuo.</p></div><div className="grid gap-3 sm:grid-cols-2">{productFeatures.slice(0,6).map(({icon:Icon,title,text})=><article key={title} className="rounded-2xl border border-white/[.08] bg-white/[.025] p-6"><Icon size={20} className="text-[#dfff65]"/><h3 className="mt-8 font-semibold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-white/42">{text}</p></article>)}</div></div></div></section>

      <section className="px-5 py-24 md:px-8 md:py-36"><div className="mx-auto max-w-[1440px]"><div data-reveal className="text-center"><p className="text-xs font-semibold uppercase tracking-[.22em] text-[#dfff65]">Empieza pequeño. Crece sin rehacer.</p><h2 className="mx-auto mt-5 max-w-5xl text-[clamp(3rem,7vw,7rem)] font-semibold leading-[.86] tracking-[-.07em]">Un plan para cada nivel de ambición.</h2></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{plans.slice(0,3).map(plan=><article key={plan.name} className={`relative rounded-[2rem] border p-7 md:p-8 ${plan.featured?"border-[#dfff65]/40 bg-[#dfff65] text-[#111407]":"border-white/[.09] bg-white/[.025]"}`}>{plan.featured&&<span className="absolute right-6 top-6 rounded-full bg-black px-3 py-1 text-[10px] font-semibold uppercase tracking-wider text-white">Recomendado</span>}<p className={`text-xs font-semibold uppercase tracking-[.18em] ${plan.featured?"text-black/55":"text-white/35"}`}>{plan.eyebrow}</p><h3 className="mt-5 text-2xl font-semibold">{plan.name}</h3><p className="mt-7 text-5xl font-semibold tracking-[-.06em]">{plan.price}</p><p className={`mt-1 text-xs ${plan.featured?"text-black/50":"text-white/35"}`}>{plan.period}</p><ul className="mt-8 space-y-3">{plan.benefits.slice(0,5).map(item=><li key={item} className={`flex gap-3 text-sm ${plan.featured?"text-black/70":"text-white/55"}`}><Check size={16} className="shrink-0"/>{item}</li>)}</ul><Link href="/pricing" className={`mt-8 inline-flex min-h-12 w-full items-center justify-center rounded-full text-sm font-semibold ${plan.featured?"bg-black text-white":"bg-white text-black"}`}>Ver plan</Link></article>)}</div></div></section>

      <section className="px-5 pb-20 md:px-8 md:pb-28"><div className="mx-auto max-w-[1440px] overflow-hidden rounded-[2.5rem] bg-[#dfff65] px-6 py-16 text-[#111407] md:px-14 md:py-24"><div className="grid gap-10 lg:grid-cols-[1.3fr_.7fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-black/50">Tu siguiente versión empieza aquí</p><h2 className="mt-5 max-w-5xl text-[clamp(3.4rem,8vw,8rem)] font-semibold leading-[.82] tracking-[-.078em]">Haz que se vea tan grande como quieres llegar.</h2></div><div><p className="text-lg leading-relaxed text-black/58">Elige una dirección, cambia el contenido y publica una presencia completa en menos tiempo del que toma explicar el brief.</p><Link href="/register" className="mt-8 inline-flex min-h-13 items-center gap-3 rounded-full bg-black px-6 font-semibold text-white">Crear con Vexora<ArrowRight size={18}/></Link></div></div></div></section>
    </main>
    <MarketingFooter/>
  </div>;
}

function ProductStage() {
  return <div className="relative mx-auto mt-16 max-w-6xl"><div className="absolute -inset-16 -z-10 bg-[radial-gradient(circle,rgba(132,102,255,.2),transparent_62%)] blur-2xl"/><div className="overflow-hidden rounded-[1.7rem] border border-white/12 bg-[#111218] shadow-[0_45px_120px_rgba(0,0,0,.6)]"><div className="flex h-13 items-center justify-between border-b border-white/[.08] px-4"><div className="flex items-center gap-2"><i className="size-2 rounded-full bg-[#dfff65]"/><span className="text-[10px] font-semibold text-white/45">MONOLITH AI / INICIO</span></div><span className="rounded-lg bg-violet-500 px-3 py-1.5 text-[10px] font-semibold">Publicar</span></div><div className="grid min-h-[500px] grid-cols-[220px_1fr_56px] max-md:grid-cols-[1fr]"><aside className="border-r border-white/[.08] p-4 max-md:hidden"><p className="text-[9px] uppercase tracking-[.16em] text-white/28">Páginas · 3</p><div className="mt-3 space-y-1">{["Inicio","Servicios","Nosotros"].map((item,index)=><div key={item} className={`flex min-h-10 items-center gap-2 rounded-lg px-3 text-[11px] ${index===0?"bg-white/[.08] text-white":"text-white/35"}`}><Layers3 size={13}/>{item}</div>)}</div><p className="mt-6 text-[9px] uppercase tracking-[.16em] text-white/28">Secciones</p><div className="mt-3 space-y-1">{["Hero principal","Capacidades","Resultados","CTA"].map(item=><div key={item} className="flex min-h-10 items-center gap-2 rounded-lg px-3 text-[11px] text-white/40"><MousePointer2 size={12}/>{item}</div>)}</div></aside><div className="relative m-3 overflow-hidden rounded-xl bg-[#090a11] p-7 md:m-5 md:p-11"><div className="absolute right-[5%] top-[2%] size-72 rounded-full bg-violet-500/25 blur-[90px]"/><p className="relative text-[9px] uppercase tracking-[.25em] text-[#dfff65]">AI systems / 2026</p><h2 className="relative mt-24 max-w-4xl text-[clamp(3rem,7vw,7.5rem)] font-semibold leading-[.82] tracking-[-.075em]">Intelligence, made operational.</h2><div className="relative mt-16 grid gap-2 sm:grid-cols-3">{["Observe","Reason","Act"].map(item=><div key={item} className="rounded-xl border border-white/10 bg-white/[.035] p-4 text-xs text-white/55">{item}</div>)}</div></div><aside className="border-l border-white/[.08] p-3 max-md:hidden"><div className="grid gap-2">{[0,1,2,3].map(index=><span key={index} className={`grid aspect-square place-items-center rounded-lg ${index===0?"bg-[#dfff65] text-black":"text-white/25"}`}><MousePointer2 size={14}/></span>)}</div></aside></div></div><div className="absolute -bottom-6 left-[8%] rounded-2xl border border-white/10 bg-[#171820]/95 p-4 shadow-2xl backdrop-blur-xl"><p className="flex items-center gap-2 text-[10px] text-white/45"><span className="size-2 rounded-full bg-emerald-400"/>Todos los cambios guardados</p><p className="mt-2 text-sm font-semibold">3 páginas listas para publicar</p></div></div>;
}
